-- Lisää DROP TABLE lauseet tähän tiedostoon
DROP TABLE IF EXISTS Game CASCADE;
DROP TABLE IF EXISTS Location CASCADE;
DROP TABLE IF EXISTS Player CASCADE;
DROP TABLE IF EXISTS Participation CASCADE;
